app:
  token:
    expire-in-minutes: 5
  allowed-api: http://localhost:8080
  minio:
    endpoint: ${APP_MINIO_ENDPOINT}
    accesskey: ${APP_MINIO_ACCESSKEY}
    secretkey: ${APP_MINIO_SECRETKEY}
    bucketname: ${APP_MINIO_BUCKETNAME}

server:
  servlet:
    context-path: /
  error:
    include-stacktrace: on_param

spring:
  application:
    name: processo-seletivo-api
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}